//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPhuKien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tPhuKien()
        {
            this.tThanhPhans = new HashSet<tThanhPhan>();
        }
    
        public string mapk { get; set; }
        public string tenpk { get; set; }
        public string manuoc { get; set; }
        public Nullable<double> dongia { get; set; }
        public Nullable<int> soluongtontai { get; set; }
        public string ghichu { get; set; }
    
        public virtual tNuocSX tNuocSX { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tThanhPhan> tThanhPhans { get; set; }
    }
}
