//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tThanhPhan
    {
        public string mathanhphan { get; set; }
        public string maxe { get; set; }
        public string mapk { get; set; }
        public string donvitinh { get; set; }
        public Nullable<int> soluong { get; set; }
    
        public virtual tPhuKien tPhuKien { get; set; }
        public virtual tXe tXe { get; set; }
    }
}
