//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tXe
    {
        internal string maXe;
        internal string tenXe;
        internal string ghiChu;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tXe()
        {
            this.tPhanCongs = new HashSet<tPhanCong>();
            this.tThanhPhans = new HashSet<tThanhPhan>();
        }
    
        public string maxe { get; set; }
        public string tenxe { get; set; }
        public string ghichu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPhanCong> tPhanCongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tThanhPhan> tThanhPhans { get; set; }
    }
}
