//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyNhaMay
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PhanXuongEntities : DbContext
    {
        public PhanXuongEntities()
            : base("name=PhanXuongEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tNuocSX> tNuocSX { get; set; }
        public virtual DbSet<tPhanCong> tPhanCong { get; set; }
        public virtual DbSet<tPhuKien> tPhuKien { get; set; }
        public virtual DbSet<tThanhPhan> tThanhPhan { get; set; }
        public virtual DbSet<tTho> tTho { get; set; }
        public virtual DbSet<tXe> tXe { get; set; }
    }
}
