//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyNhaMay
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPhanCong
    {
        public string maphancong { get; set; }
        public string matho { get; set; }
        public string maxe { get; set; }
    
        public virtual tTho tTho { get; set; }
        public virtual tXe tXe { get; set; }
    }
}
